# Generated by Django 3.1 on 2020-08-09 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Alps',
                'verbose_name_plural': 'Alps',
            },
        ),
        migrations.CreateModel(
            name='AmalfiCoast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Amalfi Coast',
                'verbose_name_plural': 'Amalfi Coast',
            },
        ),
        migrations.CreateModel(
            name='AngkorWat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Angkor Wat',
                'verbose_name_plural': 'Angkor Wat',
            },
        ),
        migrations.CreateModel(
            name='ArcDeTriomphe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Arc de Triomphe',
                'verbose_name_plural': 'Arc de Triomphe',
            },
        ),
        migrations.CreateModel(
            name='BoraBora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Bora Bora',
                'verbose_name_plural': 'Bora Bora',
            },
        ),
        migrations.CreateModel(
            name='BuckinghamPalace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Buckingham Palace',
                'verbose_name_plural': 'Buckingham Palace',
            },
        ),
        migrations.CreateModel(
            name='BurjKhalifa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Burj Khalifa',
                'verbose_name_plural': 'Burj Khalifa',
            },
        ),
        migrations.CreateModel(
            name='Colosseum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Colosseum',
                'verbose_name_plural': 'Colosseum',
            },
        ),
        migrations.CreateModel(
            name='EiffelTower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Eiffel Tower',
                'verbose_name_plural': 'Eiffel Tower',
            },
        ),
        migrations.CreateModel(
            name='GreatBarrierReef',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Great Barrier Reef',
                'verbose_name_plural': 'Great Barrier Reef',
            },
        ),
        migrations.CreateModel(
            name='LouvreMuseum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Louvre Museum',
                'verbose_name_plural': 'Louvre Museum',
            },
        ),
        migrations.CreateModel(
            name='MachuPicchu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Machu Picchu',
                'verbose_name_plural': 'Machu Picchu',
            },
        ),
        migrations.CreateModel(
            name='SydneyOperaHouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Sydney Opera House',
                'verbose_name_plural': 'Sydney Opera House',
            },
        ),
        migrations.CreateModel(
            name='TajMahal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Taj Mahal',
                'verbose_name_plural': 'Taj Mahal',
            },
        ),
        migrations.CreateModel(
            name='UyuniSaltFlat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Uyuni Salt Flat',
                'verbose_name_plural': 'Uyuni Salt Flat',
            },
        ),
    ]
