# Generated by Django 3.1 on 2020-08-09 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Australia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Australia',
                'verbose_name_plural': 'Australia',
            },
        ),
        migrations.CreateModel(
            name='Brazil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Brazil',
                'verbose_name_plural': 'Brazil',
            },
        ),
        migrations.CreateModel(
            name='France',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'France',
                'verbose_name_plural': 'France',
            },
        ),
        migrations.CreateModel(
            name='Germany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Germany',
                'verbose_name_plural': 'Germany',
            },
        ),
        migrations.CreateModel(
            name='India',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'India',
                'verbose_name_plural': 'India',
            },
        ),
        migrations.CreateModel(
            name='Spain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Spain',
                'verbose_name_plural': 'Spain',
            },
        ),
        migrations.CreateModel(
            name='Turkey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Turkey',
                'verbose_name_plural': 'Turkey',
            },
        ),
        migrations.CreateModel(
            name='USA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'USA',
                'verbose_name_plural': 'USA',
            },
        ),
    ]
