project = 'Admin Favorite'
copyright = '2020, Achintya Ranjan Chaudhary'
author = 'Achintya Ranjan Chaudhary'
version = '1.0'
release = '1.0'
templates_path = ['_templates']
source_suffix = '.rst'
master_doc = 'index'
pygments_style = 'sphinx'
html_theme = 'alabaster'
html_static_path = ['_static']