# Generated by Django 3.1 on 2020-08-09 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Africa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Africa',
                'verbose_name_plural': 'Africa',
            },
        ),
        migrations.CreateModel(
            name='Antarctica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Antarctica',
                'verbose_name_plural': 'Antarctica',
            },
        ),
        migrations.CreateModel(
            name='Asia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Asia',
                'verbose_name_plural': 'Asia',
            },
        ),
        migrations.CreateModel(
            name='Australia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Australia',
                'verbose_name_plural': 'Australia',
            },
        ),
        migrations.CreateModel(
            name='Europe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Europe',
                'verbose_name_plural': 'Europe',
            },
        ),
        migrations.CreateModel(
            name='NorthAmerica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'North America',
                'verbose_name_plural': 'North America',
            },
        ),
        migrations.CreateModel(
            name='SouthAmerica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'South America',
                'verbose_name_plural': 'South America',
            },
        ),
    ]
