# Generated by Django 3.1 on 2020-08-07 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(default=1)),
                ('model', models.ForeignKey(db_column='fm_entity_id', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Entity Type')),
            ],
        ),
    ]
